source 'https://rubygems.org'

gem 'jekyll', '~> 4.0', '>= 4.0.0'
gem 'jekyll-paginate'
gem 'octokit'
gem 'kramdown', '~> 2.3', '>= 2.3.0' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge', '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 's3_website'
gem 'sprockets-es6'
gem 'jekyll-assets', '~>2.2'
