source 'https://rubygems.org'

gem 'jekyll', '~> 3.9', '>= 3.9.0'
gem 'jekyll-paginate'
gem 'octokit'
gem 'kramdown', '~> 2.3', '>= 2.3.1' # _plugins/jekyll_ext.rb messes with internals
gem 'rouge', '<2' # rouge2 will require changes in _plugins/jekyll_ext.rb
gem 's3_website'
gem 'sprockets-es6'
gem 'jekyll-assets', '~> 2.2', '>= 2.2.7'
